### PR TITLE
Update content

### PR DESCRIPTION
**Pull request by kr8n3r**
# What

As PaaS is being [decommissioned](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/), it no longer makes sense for our product pages to sign post trial accounts and features for prospective tenants.

Updates include
- reworked homepage to include decommission notice
- removal of masthead
- removal of Pricing, Features and Get started sections
- link updates in the Footer
- cleanup of redundant files

# How to review

- [run locally ](https://github.com/alphagov/paas-product-pages/blob/main/README.md#local-development)

Homepage

localhost_3000_ (3)

### CODE REVIEW

**Review by cadmiumcat — APPROVED** [review]
bye bye new users. Looks sensible

**Review by cadmiumcat — CHANGES_REQUESTED** [review]
Changes/discussion going on in the ticket

**Comment by pauldougan** [comment]
we have finalised the copy in the google doc ready for transferring across

also can we have links in the left hand menu at the bottom that link to 
- features
- pricing 
so that these things are still navigable, thanks

**Comment by kr8n3r** [comment]
copy updated
footer links added

**Comment by pauldougan** [comment]
@kr8n3r have tested locally and looks good to me.

**Review by cadmiumcat — APPROVED** [review]
Looks good to me. Not sure what the decision is on pricing and links though

**Comment by kr8n3r** [comment]
> Looks good to me. Not sure what the decision is on pricing and links though

well, keep for now (until the end probs)

**Pull request merged**
