### PR TITLE
Remove tenant logos

### PR DESCRIPTION
**Pull request by kr8n3r**
## What and why

This removes tenant logos displayed on the homepage as well as source files and CSS snippets.

We have lots of tenants but only display a few, JPEG logos which next to text bring very little value.

We could later look at showing the list in the admin interface on the /performance page.

Additionally this change will save us 5 HTTP request and ~46KB

### Before

before

### After

after

### CODE REVIEW

**Comment by AP-Hunt** [comment]
Not sure how to feel about this. I can see it both ways. Is there guidance anywhere?

**Comment by kr8n3r** [comment]
> Not sure how to feel about this. I can see it both ways. Is there guidance anywhere?

guidance on what?

**Comment by AP-Hunt** [comment]
When/where we should be using images for stuff like this

**Comment by kr8n3r** [comment]
the closest guidance we have is "Avoid unnecessary decoration. Only use images if there’s a real user need." 
https://design-system.service.gov.uk/styles/images/

**Review by AP-Hunt — APPROVED** [review]
Yikes, I totally whiffed on this one, eh? Sorry about that. Based on that guidance, yeah, approved.

**Pull request merged**
